apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gpt-pod
  template:
    metadata:
      labels:
        app: gpt-pod
    spec:
      containers:
      - name: gptcontainer
        image: my-app:latest   # <-- use your Minikube image
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mylb
spec:
  type: NodePort              # <-- NodePort works in Minikube
  selector:
    app: gpt-pod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
